export default {
  CollectionTypes: {
    ALL: 0,
    COLLECTION: 1,
    SETLIST: 2,
  },
  Tunings: {
    'Guitar(EADGBE)': { tuning: ['e/3', 'a/3', 'd/4', 'g/4', 'b/4', 'e/5'] },
    'Guitar(DADF#AD)': { tuning: ['d/3', 'a/3', 'd/4', 'f/4#', 'a/4', 'd/5'] },
    'Banjo(GDGBD)': { tuning: ['d/4', 'g/4', 'b/4', 'd/5'] },
    'Tenor Banjo(CGDA)': { tuning: ['c/4', 'g/4', 'd/5', 'a/5'] },
    'Fiddle/Mandolin(GDAE)': { tuning: ['g/3', 'd/4', 'a/4', 'e/5'] },
    'Fiddle Fingerings(GDAE)': { tuning: ['g/3', 'd/4', 'a/4', 'e/5'], showFingerings: true },
    'Cross Fiddle(AEAE)': { tuning: ['a/3', 'e/4', 'a/4', 'e/5'] },
    'Fiddle Fingerings(AEAE)': { tuning: ['a/3', 'e/4', 'a/4', 'e/5'], showFingerings: true },
  },
  SampleNotes: [
    'c3',
    'cs3',
    'd3',
    'ds3',
    'e3',
    'f3',
    'fs3',
    'g3',
    'gs3',
    'a3',
    'as3',
    'b3',
    'c4',
    'cs4',
    'd4',
    'ds4',
    'e4',
    'f4',
    'fs4',
    'g4',
    'gs4',
    'a4',
    'as4',
    'b4',
    'c5',
    'cs5',
    'd5',
    'ds5',
    'e5',
    'f5',
    'fs5',
    'g5',
    'gs5',
    'a5',
    'as5',
    'b5',
    'c6'
  ],
  PlayModes: {
    MELODY_AND_CHORDS: 0,
    CHORDS_ONLY: 1,
    MELODY_ONLY: 2,
  },
  FieldTypes: {
    INTEGER: 'integer',
    TEXT: 'text',
  }
};
